#!/bin/bash

################################################################################
#    Copyright 2009 Sun Microsystems, Inc.,
#    4150 Network Circle, Santa Clara, California 95054, U.S.A.
#    All rights reserved.
#
#    U.S. Government Rights - Commercial software.
#    Government users are subject to the Sun Microsystems, Inc. standard
#    license agreement and applicable provisions of the FAR and its supplements.
#
#    Use is subject to license terms.
#
#    This distribution may include materials developed by third parties.
#
#    Sun, Sun Microsystems, the Sun logo and Java are trademarks or registered
#    trademarks of Sun Microsystems, Inc. in the U.S. and other countries.
################################################################################

# Takes as input a sequence of lines, each containing, somewhere, 
# non_empty_user_name@non_empty_host
# if there is more than one @ on the line, results are not so good.
# The three sed lines are, roughly:
#  trim off leading gunk, up to non_empty@
#  trim off trailing gunk, possibly leaving some trailing whitespace
#  trim off trailing whitespace

sed -E -e '1,$s/^([ 	]*)([^ 	@]+[ 	]+)*<?//g' |
sed -E -e '1,$s/>?([ 	]+[^ 	@]+)*$//g' |
sed -E -e '1,$s/[ 	]+$//g'
