#!/bin/bash

################################################################################
#    Copyright 2007 Sun Microsystems, Inc.,
#    4150 Network Circle, Santa Clara, California 95054, U.S.A.
#    All rights reserved.
#
#    U.S. Government Rights - Commercial software.
#    Government users are subject to the Sun Microsystems, Inc. standard
#    license agreement and applicable provisions of the FAR and its supplements.
#
#    Use is subject to license terms.
#
#    This distribution may include materials developed by third parties.
#
#    Sun, Sun Microsystems, the Sun logo and Java are trademarks or registered
#    trademarks of Sun Microsystems, Inc. in the U.S. and other countries.
################################################################################

if [ "$ANT_HOME" == "" ] ; then
  export TMPDIR="$$".tmpdir
  mkdir /tmp/$TMPDIR

  ANT_HOME=`(cd /tmp/$TMPDIR; ant -diagnostics | sed -n -e 's/^ant\.home: //p' | head -1)`

  rmdir /tmp/$TMPDIR

  echo please set ANT_HOME, guessing $ANT_HOME
else
  echo ANT_HOME is $ANT_HOME
fi

#
# For NetBeans, you should not need to adjust anything to
# build and test Fortress.
#
# For Eclipse, workspace and ant builds should not require any
# adjustments, but to run tests using ant within Eclipse, you
# will need to add junit.jar to
# build.xml -> Run As -> Ant Build... -> Classpath -> User Entries -> Add JARs...
#
$ANT_HOME/bin/ant -noclasspath -lib third_party/junit "$@"
