#!/bin/bash

################################################################################
#    Copyright 2007 Sun Microsystems, Inc.,
#    4150 Network Circle, Santa Clara, California 95054, U.S.A.
#    All rights reserved.
#
#    U.S. Government Rights - Commercial software.
#    Government users are subject to the Sun Microsystems, Inc. standard
#    license agreement and applicable provisions of the FAR and its supplements.
#
#    Use is subject to license terms.
#
#    This distribution may include materials developed by third parties.
#
#    Sun, Sun Microsystems, the Sun logo and Java are trademarks or registered
#    trademarks of Sun Microsystems, Inc. in the U.S. and other countries.
################################################################################

#
# For NetBeans, you should not need to adjust anything to
# build and test Fortress.
#
# For Eclipse, workspace and ant builds should not require any
# adjustments, but to run tests using Ant within Eclipse, you
# will need to add junit.jar to
# build.xml -> Run As -> Ant Build... -> Classpath -> User Entries -> Add JARs...
#

find_ant(){

  # if $ANT_HOME is set then search for ant there
  if [ "x$ANT_HOME" != "x" ]; then
    if [ -x "$ANT_HOME/bin/ant" ]; then
      echo $ANT_HOME/bin/ant
      return
    else
      echo "Did not find ant in $ANT_HOME/bin" >&2
    fi
  else
    echo "ANT_HOME is not set" >&2
  fi

  # Otherwise use whatever is in $PATH
  result=`which ant 2>/dev/null`
  if [ -z "$result" ]; then
    echo "Could not find ant. You need to install it. See http://ant.apache.org/ for details." >&2
    exit 1
  fi
  echo $result
  exit 0
}

ant_exec=`find_ant`
n=$?
if [ $n -ne 0 ]; then
        exit $n
fi
$ant_exec -noclasspath -lib third_party/junit "$@"
