#!/bin/bash

################################################################################
#    Copyright 2008 Sun Microsystems, Inc.,
#    4150 Network Circle, Santa Clara, California 95054, U.S.A.
#    All rights reserved.
#
#    U.S. Government Rights - Commercial software.
#    Government users are subject to the Sun Microsystems, Inc. standard
#    license agreement and applicable provisions of the FAR and its supplements.
#
#    Use is subject to license terms.
#
#    This distribution may include materials developed by third parties.
#
#    Sun, Sun Microsystems, the Sun logo and Java are trademarks or registered
#    trademarks of Sun Microsystems, Inc. in the U.S. and other countries.
################################################################################

if (uname | egrep -q CYGWIN) ; then 
  CP="build;third_party/junit/junit.jar;third_party/unsigned/unsigned.jar;third_party/asm/asm-3.1.jar;third_party/xtc/xtc.jar;third_party/jsr166y/jsr166y.jar;third_party/plt/plt.jar;third_party/astgen/astgen.jar"
else
  CP="build:third_party/junit/junit.jar:third_party/unsigned/unsigned.jar:third_party/asm/asm-3.1.jar:third_party/xtc/xtc.jar:third_party/jsr166y/jsr166y.jar:third_party/plt/plt.jar:third_party/astgen/astgen.jar"
fi



java -cp "$CP" -Xmx800m -Xms400m \
junit.swingui.TestRunner \
com.sun.fortress.tests.unit_tests.SystemJUTest >& test.log
