/*******************************************************************************
    Copyright 2007 Sun Microsystems, Inc.,
    4150 Network Circle, Santa Clara, California 95054, U.S.A.
    All rights reserved.

    U.S. Government Rights - Commercial software.
    Government users are subject to the Sun Microsystems, Inc. standard
    license agreement and applicable provisions of the FAR and its supplements.

    Use is subject to license terms.

    This distribution may include materials developed by third parties.

    Sun, Sun Microsystems, the Sun logo and Java are trademarks or registered
    trademarks of Sun Microsystems, Inc. in the U.S. and other countries.
 ******************************************************************************/

package com.sun.fortress.interpreter.nodes;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class InterfaceMaker {
    private static final String INDENT = "    ";

    private static boolean commented(String line) {
        return line.matches("#.*");
    }

    private static String removeDots(String line) {
        return line.replace(".","");
    }

    public static void makeNodeVisitor(BufferedReader lines) throws IOException {
        System.out.println("/* THIS FILE WAS AUTOMATICALLY GENERATED BY InterfaceMaker.java FROM leafclasses */");
        System.out.println("package com.sun.fortress.interpreter.nodes;");
        System.out.println("public interface NodeVisitor<T> {");

        String line = lines.readLine();
        while (line != null) {
            if (! commented(line)) {
                System.out.println(INDENT + "T for" + removeDots(line) +"(" + line +" x);");
            }
            line = lines.readLine();
        }
        System.out.println("}");
    }

    public static void main(String[] args) throws IOException {
        if (args.length != 1) {
            throw new RuntimeException("Expected exactly one filename as an argument");
        }
        makeNodeVisitor(new BufferedReader(new FileReader(args[0])));
    }

}
