/*******************************************************************************
    Copyright 2008,2009, Oracle and/or its affiliates.
    All rights reserved.


    Use is subject to license terms.

    This distribution may include materials developed by third parties.

 ******************************************************************************/

package com.sun.fortress.exceptions;

import com.sun.fortress.nodes.FnDecl;
import com.sun.fortress.nodes.TraitObjectDecl;
import com.sun.fortress.useful.HasAt;

/**
 * A static error generated by the type checker.
 */
public class TypeError extends StaticError {

    protected TypeError() {
        // Here just so that subclasses don't need a description and location.
    }

    protected TypeError(String description, HasAt location) {
        super(description, location);
    }

    /** Make Eclipse happy */
    private static final long serialVersionUID = -3586975274806304888L;

    /**
     * Make a simple static error with the given location.
     */
    public static StaticError make(String description, HasAt location) {
        return new TypeError(description, location);
    }
    
    public static void b0() { 
        return;
    }
    public static void b1(Object a) { 
        return;
    }
    public static void b2(Object a, Object b) {
        return;
    }
    public static void b3(Object a, Object b, Object c) {
        if (b instanceof TraitObjectDecl) {
        TraitObjectDecl tod = (TraitObjectDecl) b;
        String s = tod.getHeader().getName().stringName();
        return;
        }
        return;
    }
    public static void b4(Object a, Object b, Object c, Object d) {
        return;
    }
    public static void b5(Object a, Object b, Object c, Object d, Object e) {
        return;
    }
}
