/*******************************************************************************
    Copyright 2011 Oracle and/or its affiliates.
    All rights reserved.


    Use is subject to license terms.

    This distribution may include materials developed by third parties.

******************************************************************************/
package com.sun.fortress.compiler.asmbytecodeoptimizer;

// This class is for creating temporary place holder values which will eventually be merged
// with real AbstractValues generated by abstract interpretation.

public class AbstractInterpretationPlaceHolder extends AbstractInterpretationValue{
    AbstractInterpretationValue realValue;
    
    AbstractInterpretationPlaceHolder(Insn definition, String type) {
        super(definition,type);
    }
    
    public void setRealValue(AbstractInterpretationValue v) {
        if (getType().equals(v.getType()) | getType().equals(""))
            realValue = v;
        else throw new RuntimeException("RuhRohRaggy");
    }

    public String idString() {
        if (realValue != null)
            return "AbstractInterpretationPlaceHolder for " + realValue.getValueNumber();
        else return "AbstractInterpretationPlaceHolder " + getValueNumber();
    }
}